#!/bin/bash
xdg-open ~/\[FCO\]\ AppliedAICourse\ -\ Applied\ Machine\ Learning\ Course/
cd ~/Desktop/notes/
xdg-open MachineLearningNotes_KarthikKumarBilla.pdf
xdg-open Applied\ AI-Machine\ Learning\ course\ syllabus.pdf
cd ~/python_notebooks/
eval "$(conda shell.bash hook)"
conda activate
jupyter notebook

